server:
  port: 8082


spring:
  thymeleaf:
    mode: HTML5
  datasource:
    #url: jdbc:mysql://localhost:3306/db_jobanalysis?serverTimezone=UTC
    url: jdbc:mysql://118.126.110.120:3306/test?serverTimezone=UTC
    username: root
    password: zb104207
    driver-class-name: com.mysql.jdbc.Driver

  #security:
    #basic:
      #enabled: false

#mybatis:
#    mapperLocations : classpath:com/swpu/jobanalysissystem/*.xml
mybatis:
  #实体类所做包
  type-aliases-package: learning.model2
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml


#这个配置可以用
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#log4j2
Configuration:
  status: warn

  Properties: # 定义变量
    Property:
      - name: log.path
        value: d:\\tmp\\logs
      - name: project.name
        value: spring-boot-log

  Appenders:
    Console:  #输出到控制台
      name: CONSOLE
      target: SYSTEM_OUT
      ThresholdFilter:
        level: trace
        onMatch: ACCEPT
        onMismatch: DENY
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"

    # 输出到文件，超过128MB归档
    RollingFile:
      - name: ROLLING_FILE
        ignoreExceptions: false
        fileName: ${log.path}/${project.name}.log
        filePattern: "${log.path}/$${date:yyyy-MM}/${project.name}-%d{yyyy-MM-dd}-%i.log.gz"
        PatternLayout:
          pattern: "%d{yyyy-MM-dd HH:mm:ss,SSS}:%4p %t (%F:%L) - %m%n"
        Policies:
          SizeBasedTriggeringPolicy:
            size: "128 MB"
        DefaultRolloverStrategy:
          max: 1000

  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: CONSOLE
        - ref: ROLLING_FILE
    Logger: # 为com.xjj包配置特殊的Log级别，方便调试
      - name: com.test.dao
        additivity: false
        level: debug
        AppenderRef:
          - ref: CONSOLE
          - ref: ROLLING_FILE